import Head from 'next/head';
import { useQuery } from 'urql';
import { PRODUCT_QUERY } from '../lib/query';
import Product from "../components/Products";
import {Gallery} from "../styles/Gallery";
import Nav from '../components/Nav';

export default function Home() {
//fetch products from strapi
  const [results] = useQuery({query: PRODUCT_QUERY});
  const {data, fetching, error} = results;

  //check for the data coming in
  if(fetching) return <p>Loading...</p>;
  if(error) return <p>Oh no... {error.message}</p> ;
  const products = data.products.data;
  //console.log(products);
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Gallery>
        {products.map((product) => (
          <Product key={product.attributes.slug} product={product}/>
        ))}
        </Gallery>
      </main>
    </>
  )
}
